server:
  port: ${PORT} #Porta em que a aplicação ira rodar.

spring:
  cloud:
    config:
      server:
        git: #Configuração para acessar repositório do git hub, referente ao arquivo application-dev.yaml global para aplicação.
          uri: https://github.com/vinizuppa/ead-config-server-repo #URI do repositório
          default-label: main #Branch
            username: ${GIT_USERNAME} #Caso o repositório do application-dev.yaml fosse privado
            password: ${GIT_PASSWORD} #Criar personal access token #Caso o repositório do application-dev.yaml fosse privado
encrypt:
  key: v8y/A?D(G+KbPeShVmYq3t6w9z$C&E)H@McQfTjWnZr4u7x!A%D*G-JaNdRgUkXp


ead:
  configServer:
    username: ${CONFIG_SERVER_USERNAME}
    password: ${CONFIG_SERVER_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    instance:
      hostname: ${APP_DOMAIN_NAME}
      non-secure-port: 80
